axon:
  axonserver:
    enabled: false
  kafka:
    bootstrap-servers: localhost:29092,localhost:29094,localhost:29096
    default-topic: Axon.AccountCQRS.Events
    client-id: kafka-axon-account
    message-converter-mode: default # alternative is cloud_event <https://cloudevents.io/>
    properties:
      security.protocol: PLAINTEXT # PLAINTEXT for no security purpose
    publisher:
      confirmation-mode: transactional
    producer:
      transaction-id-prefix: kafka-axon-
      retries: 5 # bigger than zero in case of using transactional confirmation-mode
      event-processor-mode: tracking
#    consumer:
#      event-processor-mode: subscribing
#      properties:
#        isolation.level: read_committed
    consumer:
      event-processor-mode: tracking
      properties:
        isolation.level: read_committed

  serializer:
    general: jackson
    events: jackson
    messages: jackson
eureka:
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true

server:
  port: 20260
spring:
  application:
    name: account
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    username: itpusr
    password: itp@168
    url: jdbc:postgresql://localhost:16851/db_account
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

  r2dbc:
    url: r2dbc:postgresql://localhost:16851/db_account
    username: itpusr
    password: itp@168

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090

customer-service:
  url: http://localhost:20261